init:
	terraform init

fmt:
	terraform fmt

console:
	terraform console

plan:
	terraform plan

apply:
	terraform apply -auto-approve

destroy:
	terraform destroy -auto-approve

refresh:
	terraform apply -auto-approve -refresh-only

list:
	terraform state list

output:
	terraform output